### ISSUE TITLE
Sending money to new contact causes app to crash

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/hugin-mobile#13]
When going to the wallet view by pressing the wallet button and pressing "add new contact", then filling in information about name, payment address and message key and pressing "continue" caused the app to crash.

**Comment by f-r00t** [comment]
Tried this on two different devices with both dev version, the latest apk and downloaded from Play store, and have not been able to reproduce the issue. Not sure how to move forward with this issue.

**Comment by f-r00t** [comment]
Should be fixed in 0.0.4.
