### ISSUE TITLE
Message failed to send. Tap here to try again 

### ISSUE THREAD

**Issue by Gegegega** [kryptokrona/hugin-mobile#54]
In the latest version of hugin, I can send 4-5 messages after synchronizing my wallet again, but after that, I will always fail to send them.  After I return my wallet, the locked 0.0561 xkr is not displayed.
  
 I wonder why not an integer xkr is locked, but because of so many bits and pieces.
  
 I have been unable to use the latest version of hugin normally on mobile phone.  Failed to send all the time, the following is the log:
["[09:37:07]: Network connection changed. Restarting sync process if needed.","[09:37:08]: Updated coin price from API","[09:37:08]: PRICE:0.0029987041542368018","[09:37:11]: Threw exception processing tick function: TypeError: JSON.stringify(u).replaceAll is not a function. (In 'JSON.stringify(u).replaceAll('transactionPrefixInfo.txPrefix','transactionPrefixInfo')', 'JSON.stringify(u).replaceAll' is undefined)","[09:37:12]: Getting unconfirmed transactions...","[09:37:17]: Getting unconfirmed transactions...","[09:37:22]: Getting unconfirmed transactions...","[09:37:24]: Threw exception processing tick function: TypeError: JSON.stringify(u).replaceAll is not a function. (In 'JSON.stringify(u).replaceAll('transactionPrefixInfo.txPrefix','transactionPrefixInfo')', 'JSON.stringify(u).replaceAll' is undefined)","[09:37:27]: Getting unconfirmed transactions...","[09:37:32]: Getting unconfirmed transactions...","[09:37:37]: Getting unconfirmed transactions...","[09:37:38]: Threw exception processing tick function: TypeError: JSON.stringify(u).replaceAll is not a function. (In 'JSON.stringify(u).replaceAll('transactionPrefixInfo.txPrefix','transactionPrefixInfo')', 'JSON.stringify(u).replaceAll' is undefined)","[09:37:42]: Getting unconfirmed transactions...","[09:38:30]: Getting unconfirmed transactions...","[09:38:30]: Saving wallet...","[09:38:30]: Save complete.","[09:38:33]: Threw exception processing tick function: TypeError: JSON.stringify(u).replaceAll is not a function. (In 'JSON.stringify(u).replaceAll('transactionPrefixInfo.txPrefix','transactionPrefixInfo')', 'JSON.stringify(u).replaceAll' is undefined)","[09:38:35]: Getting unconfirmed transactions...","[09:39:13]: Getting unconfirmed transactions..."]

**Comment by Gegegega** [comment]
In addition, in the group message reminder on the homepage of hugin, there is always a prompt that there is a new message, but after clicking in, there is no new message, even if it is a message sent by myself

**Comment by Gegegega** [comment]
During this process, my nodes are connected normally and the blocks are synchronized to 100 %

**Comment by f-r00t** [comment]
Hello. Have you tried using a new account? Old accounts may suffer from some bad states due to inefficient splitting of inputs in earlier versions of Hugin. When trying new accounts, we have not been able to replicate your issue, and can send messages until all XKR is locked up (until it is unlocked 24h later).

Touching on your incorrect balance, I take it you expect to see 0.0561 XKR in the balance. First of all, why do you expect to see that specific amount? And what do you see instead? This is also possibly correlated to using an account use with older versions of Hugin. Also it could possibly be correlated to using the same account (private key) on both Hugin Desktop and Hugin Mobile. Are you doing that? In so we can investigate further.

Thanks!

**Comment by Gegegega** [comment]
What do you mean by new and old accounts?
Are you saying that if a new wallet is rebuilt, this problem will not occur, while a wallet created before the release of this version will have this problem when used?
I only used Hugin on my phone, and this wallet did not log in to my PC.

**Comment by Gegegega** [comment]
> Hello. Have you tried using a new account? Old accounts may suffer from some bad states due to inefficient splitting of inputs in earlier versions of Hugin. When trying new accounts, we have not been able to replicate your issue, and can send messages until all XKR is locked up (until it is unlocked 24h later).
> 
> Touching on your incorrect balance, I take it you expect to see 0.0561 XKR in the balance. First of all, why do you expect to see that specific amount? And what do you see instead? This is also possibly correlated to using an account use with older versions of Hugin. Also it could possibly be correlated to using the same account (private key) on both Hugin Desktop and Hugin Mobile. Are you doing that? In so we can investigate further.
> 
> Thanks!

What do you mean by new and old accounts?
Are you saying that if a new wallet is rebuilt, this problem will not occur, while a wallet created before the release of this version will have this problem when used?
I only used Hugin on my phone, and this wallet did not log in to my PC.

**Comment by f-r00t** [comment]
Hello again!

Yes, using the same account with an older version of Hugin Mobile might be a factor, so please let us know if this is indeed an old account and if you are facing the same issues when using a brand new account.

Thanks.

**Comment by Gegegega** [comment]
I created my wallet with the old version of Hugin and logged in to the new version.  Do I need to download a new version, then create a new wallet, and transfer the xkr of the old wallet to the new wallet for use？

**Comment by f-r00t** [comment]
Continued in https://github.com/kryptokrona/hugin-mobile/issues/60
